apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvww7b5lh-java-quarkus
  janus-idp.io/tekton: zvww7b5lh-java-quarkus
  backstage.io/kubernetes-id: zvww7b5lh-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zvww7b5lh-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
